
"""add refresh token table

Revision ID: 0e83e6c91c1c
Revises: a3849ce8f25b
Create Date: 2026-07-07 02:20:59.193804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e83e6c91c1c'
down_revision = 'a3849ce8f25b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
