
"""add_last_seen_at_to_users

Revision ID: a55a4d867116
Revises: c607f5c28195
Create Date: 2026-08-23 13:30:11.689953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55a4d867116'
down_revision = 'c607f5c28195'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    # ### end Alembic commands ###
