
"""add hunting queries table

Revision ID: bfa61a95331c
Revises: f838a5d9523b
Create Date: 2026-07-10 16:51:20.016412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa61a95331c'
down_revision = 'f838a5d9523b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_hunting_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_hunting_queries_created_at'), 'threat_hunting_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_threat_hunting_queries_name'), 'threat_hunting_queries', ['name'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_hunting_queries')
    # ### end Alembic commands ###
