
"""add_network_discovery_tables

Revision ID: c0f80578b423
Revises: a55a4d867116
Create Date: 2026-08-23 16:26:29.712520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f80578b423'
down_revision = 'a55a4d867116'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
