
"""add_user_onboarding_fields

Revision ID: c607f5c28195
Revises: bfa61a95331c
Create Date: 2026-08-23 11:08:17.823701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c607f5c28195'
down_revision = 'bfa61a95331c'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_connector', sa.String(length=100), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_logs_failed_at'), 'failed_logs', ['failed_at'], unique=False)
    op.create_index(op.f('ix_failed_logs_source_connector'), 'failed_logs', ['source_connector'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mitre_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_techniques_mitre_id'), 'mitre_techniques', ['mitre_id'], unique=True)
    op.create_table('threat_indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tlp', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_indicators_created_at'), 'threat_indicators', ['created_at'], unique=False)
    op.create_index(op.f('ix_threat_indicators_severity'), 'threat_indicators', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_indicators_source'), 'threat_indicators', ['source'], unique=False)
    op.create_index(op.f('ix_threat_indicators_type'), 'threat_indicators', ['type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_value'), 'threat_indicators', ['value'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_table('case_alerts',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'alert_id')
    )
    op.create_table('case_incidents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'incident_id')
    )
    op.create_table('case_mitre_techniques',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('mitre_technique_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mitre_technique_id'], ['mitre_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'mitre_technique_id')
    )
    op.create_table('ioc_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('raw_log_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('matched_field', sa.String(length=100), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['threat_indicators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ioc_matches_alert_id'), 'ioc_matches', ['alert_id'], unique=False)
    op.create_index(op.f('ix_ioc_matches_indicator_id'), 'ioc_matches', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_ioc_matches_matched_at'), 'ioc_matches', ['matched_at'], unique=False)
    op.create_index(op.f('ix_ioc_matches_raw_log_id'), 'ioc_matches', ['raw_log_id'], unique=False)
    op.execute('DROP TABLE IF EXISTS ioc_records CASCADE;')
    op.execute('DROP TABLE IF EXISTS threat_feeds CASCADE;')
    op.execute('DROP TABLE IF EXISTS threat_hunting_queries CASCADE;')
    op.execute('DROP TABLE IF EXISTS threat_intelligence CASCADE;')
    op.execute('DROP TABLE IF EXISTS ioc_matches CASCADE;')
    op.execute('DROP TABLE IF EXISTS case_mitre_techniques CASCADE;')
    op.execute('DROP TABLE IF EXISTS case_incidents CASCADE;')
    op.execute('DROP TABLE IF EXISTS case_alerts CASCADE;')
    op.execute('DROP TABLE IF EXISTS email_verification_tokens CASCADE;')
    op.execute('DROP TABLE IF EXISTS threat_indicators CASCADE;')
    op.execute('DROP TABLE IF EXISTS mitre_techniques CASCADE;')
    op.execute('DROP TABLE IF EXISTS failed_logs CASCADE;')
    op.add_column('raw_logs', sa.Column('source_connector', sa.String(length=100), nullable=False))
    op.add_column('raw_logs', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('raw_logs', sa.Column('severity', sa.String(length=50), nullable=False))
    op.add_column('raw_logs', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.add_column('raw_logs', sa.Column('source_ip', sa.String(length=45), nullable=True))
    op.add_column('raw_logs', sa.Column('destination_ip', sa.String(length=45), nullable=True))
    op.add_column('raw_logs', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('raw_logs', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('raw_logs', sa.Column('process_name', sa.String(length=255), nullable=True))
    op.add_column('raw_logs', sa.Column('file_hash', sa.String(length=255), nullable=True))
    op.add_column('raw_logs', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('raw_logs', sa.Column('url', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_raw_logs_log_type'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_source'), table_name='raw_logs')
    op.create_index(op.f('ix_raw_logs_destination_ip'), 'raw_logs', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_raw_logs_domain'), 'raw_logs', ['domain'], unique=False)
    op.create_index(op.f('ix_raw_logs_event_type'), 'raw_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_logs_file_hash'), 'raw_logs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_raw_logs_hostname'), 'raw_logs', ['hostname'], unique=False)
    op.create_index(op.f('ix_raw_logs_process_name'), 'raw_logs', ['process_name'], unique=False)
    op.create_index(op.f('ix_raw_logs_severity'), 'raw_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_raw_logs_source_connector'), 'raw_logs', ['source_connector'], unique=False)
    op.create_index(op.f('ix_raw_logs_source_ip'), 'raw_logs', ['source_ip'], unique=False)
    op.create_index(op.f('ix_raw_logs_timestamp'), 'raw_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_raw_logs_username'), 'raw_logs', ['username'], unique=False)
    op.drop_column('raw_logs', 'log_type')
    op.drop_column('raw_logs', 'source')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('approval_status', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('approved_by', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('rejected_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('registration_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('registration_device', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('last_login_device', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_login_device')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'registration_device')
    op.drop_column('users', 'registration_ip')
    op.drop_column('users', 'rejected_reason')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'approved_by')
    op.drop_column('users', 'approval_status')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.add_column('raw_logs', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('raw_logs', sa.Column('log_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_raw_logs_username'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_timestamp'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_source_ip'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_source_connector'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_severity'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_process_name'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_hostname'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_file_hash'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_event_type'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_domain'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_destination_ip'), table_name='raw_logs')
    op.create_index(op.f('ix_raw_logs_source'), 'raw_logs', ['source'], unique=False)
    op.create_index(op.f('ix_raw_logs_log_type'), 'raw_logs', ['log_type'], unique=False)
    op.drop_column('raw_logs', 'url')
    op.drop_column('raw_logs', 'domain')
    op.drop_column('raw_logs', 'file_hash')
    op.drop_column('raw_logs', 'process_name')
    op.drop_column('raw_logs', 'username')
    op.drop_column('raw_logs', 'hostname')
    op.drop_column('raw_logs', 'destination_ip')
    op.drop_column('raw_logs', 'source_ip')
    op.drop_column('raw_logs', 'timestamp')
    op.drop_column('raw_logs', 'severity')
    op.drop_column('raw_logs', 'event_type')
    op.drop_column('raw_logs', 'source_connector')
    op.create_table('threat_intelligence',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('threat_intelligence_pkey'))
    )
    op.create_index(op.f('ix_threat_intelligence_title'), 'threat_intelligence', ['title'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_external_id'), 'threat_intelligence', ['external_id'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_created_at'), 'threat_intelligence', ['created_at'], unique=False)
    op.create_table('ioc_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mitre_attack_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('threat_feed_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['threat_feed_id'], ['threat_feeds.id'], name=op.f('ioc_records_threat_feed_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ioc_records_pkey'))
    )
    op.create_index(op.f('ix_ioc_records_value'), 'ioc_records', ['value'], unique=True)
    op.create_index(op.f('ix_ioc_records_type'), 'ioc_records', ['type'], unique=False)
    op.create_index(op.f('ix_ioc_records_risk_score'), 'ioc_records', ['risk_score'], unique=False)
    op.create_index(op.f('ix_ioc_records_created_at'), 'ioc_records', ['created_at'], unique=False)
    op.create_table('threat_hunting_queries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('threat_hunting_queries_creator_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('threat_hunting_queries_pkey'))
    )
    op.create_index(op.f('ix_threat_hunting_queries_name'), 'threat_hunting_queries', ['name'], unique=True)
    op.create_index(op.f('ix_threat_hunting_queries_created_at'), 'threat_hunting_queries', ['created_at'], unique=False)
    op.create_table('threat_feeds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('feed_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('threat_feeds_pkey'))
    )
    op.create_index(op.f('ix_threat_feeds_name'), 'threat_feeds', ['name'], unique=True)
    op.drop_index(op.f('ix_ioc_matches_raw_log_id'), table_name='ioc_matches')
    op.drop_index(op.f('ix_ioc_matches_matched_at'), table_name='ioc_matches')
    op.drop_index(op.f('ix_ioc_matches_indicator_id'), table_name='ioc_matches')
    op.drop_index(op.f('ix_ioc_matches_alert_id'), table_name='ioc_matches')
    op.drop_table('ioc_matches')
    op.drop_table('case_mitre_techniques')
    op.drop_table('case_incidents')
    op.drop_table('case_alerts')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_threat_indicators_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_type'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_source'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_severity'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_created_at'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    op.drop_index(op.f('ix_mitre_techniques_mitre_id'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_failed_logs_source_connector'), table_name='failed_logs')
    op.drop_index(op.f('ix_failed_logs_failed_at'), table_name='failed_logs')
    op.drop_table('failed_logs')
    # ### end Alembic commands ###
