
"""add soft delete mixin to core models

Revision ID: cf98ea43541e
Revises: a259b72f63ee
Create Date: 2026-07-07 01:46:39.933591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf98ea43541e'
down_revision = 'a259b72f63ee'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_alerts_is_deleted'), 'alerts', ['is_deleted'], unique=False)
    op.add_column('cases', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('cases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cases_is_deleted'), 'cases', ['is_deleted'], unique=False)
    op.add_column('incidents', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('incidents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_incidents_is_deleted'), 'incidents', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_index(op.f('ix_incidents_is_deleted'), table_name='incidents')
    op.drop_column('incidents', 'deleted_at')
    op.drop_column('incidents', 'is_deleted')
    op.drop_index(op.f('ix_cases_is_deleted'), table_name='cases')
    op.drop_column('cases', 'deleted_at')
    op.drop_column('cases', 'is_deleted')
    op.drop_index(op.f('ix_alerts_is_deleted'), table_name='alerts')
    op.drop_column('alerts', 'deleted_at')
    op.drop_column('alerts', 'is_deleted')
    # ### end Alembic commands ###
