
"""add_security_alerts_table

Revision ID: cff8339db910
Revises: 1a0db3d3e168
Create Date: 2026-08-23 19:16:27.218002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff8339db910'
down_revision = '1a0db3d3e168'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_mac', sa.String(length=17), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['network_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['network_sensors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_alert_type'), 'security_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_security_alerts_last_seen'), 'security_alerts', ['last_seen'], unique=False)
    op.create_index(op.f('ix_security_alerts_severity'), 'security_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_security_alerts_source_ip'), 'security_alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_security_alerts_source_mac'), 'security_alerts', ['source_mac'], unique=False)
    op.create_index(op.f('ix_security_alerts_status'), 'security_alerts', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_alerts_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_source_mac'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_source_ip'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_severity'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_last_seen'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_alert_type'), table_name='security_alerts')
    op.drop_table('security_alerts')
    # ### end Alembic commands ###
