
"""add raw logs table

Revision ID: e3883c71a338
Revises: 0e83e6c91c1c
Create Date: 2026-07-07 19:15:29.468632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3883c71a338'
down_revision = '0e83e6c91c1c'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('log_type', sa.String(length=100), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parsed_content', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_logs_ingested_at'), 'raw_logs', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_raw_logs_log_type'), 'raw_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_raw_logs_source'), 'raw_logs', ['source'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_logs_source'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_log_type'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_ingested_at'), table_name='raw_logs')
    op.drop_table('raw_logs')
    # ### end Alembic commands ###
